/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DemoFormLayoutHorizontalForm: typeof import('./src/components/form-layouts/DemoFormLayoutHorizontalForm.vue')['default']
    DemoFormLayoutHorizontalFormWithIcons: typeof import('./src/components/form-layouts/DemoFormLayoutHorizontalFormWithIcons.vue')['default']
    DemoFormLayoutMultipleColumn: typeof import('./src/components/form-layouts/DemoFormLayoutMultipleColumn.vue')['default']
    DemoFormLayoutVerticalForm: typeof import('./src/components/form-layouts/DemoFormLayoutVerticalForm.vue')['default']
    DemoFormLayoutVerticalFormWithIcons: typeof import('./src/components/form-layouts/DemoFormLayoutVerticalFormWithIcons.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    HomeDialog: typeof import('./src/components/dialogs/HomeDialog.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBasic: typeof import('./src/components/tables/TableBasic.vue')['default']
    TableDark: typeof import('./src/components/tables/TableDark.vue')['default']
    TableDensity: typeof import('./src/components/tables/TableDensity.vue')['default']
    TableFixedHeader: typeof import('./src/components/tables/TableFixedHeader.vue')['default']
    TableHeight: typeof import('./src/components/tables/TableHeight.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
