/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthorityClosedTenderCard: typeof import('./src/components/cards/AuthorityClosedTenderCard.vue')['default']
    AuthorityNewTenderDialog: typeof import('./src/components/dialogs/AuthorityNewTenderDialog.vue')['default']
    AuthorityNewTenderForm: typeof import('./src/components/forms/AuthorityNewTenderForm.vue')['default']
    AuthorityTenderCard: typeof import('./src/components/cards/AuthorityTenderCard.vue')['default']
    AuthorityVicTenderCard: typeof import('./src/components/cards/AuthorityVicTenderCard.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CitizenTenderCard: typeof import('./src/components/cards/CitizenTenderCard.vue')['default']
    ConstructionMyTenders: typeof import('./src/components/cards/ConstructionMyTenders.vue')['default']
    ConstructionMyTendersCard: typeof import('./src/components/cards/ConstructionMyTendersCard.vue')['default']
    ConstructionTenderCard: typeof import('./src/components/cards/ConstructionTenderCard.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    HomeDialog: typeof import('./src/components/dialogs/HomeDialog.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
